### ISSUE TITLE
本地部署，出现如下错误，找不到原因，请求指导

### ISSUE THREAD

**Issue by soffy** [chatbookai/ChatBook#3]
1 of 1 unhandled error

Unhandled Runtime Error
AxiosError: Network Error

Call Stack
XMLHttpRequest.handleError
node_modules\axios\lib\adapters\xhr.js (158:0)

**Comment by chives-network** [comment]
说明你的网络不太确实,造成有些包传输失败造成的.
你需要一个稳定的网络环境
